/************************************************************
 * Generated by SoftTree SQL Assistant © 9.1.261
 * Time:   8/28/2019 9:39:13 PM
 * Source: TblAlbums, TblAllOrderStatus, TblAtelierType, TblBooking, TblBookingStatus, 
 *         TblCustomer, TblFilesError, TblOrder, TblOrderFiles, TblOrderPrint, TblOrderPrintDetails, 
 *         TblOrderPrintFiles, TblOrderPrintStatus, TblOrderStatus, TblPhotographyType, 
 *         TblPrintCustomerFiles, TblPrintServicePrices, TblPrintServices, TblPrintSizePrices, 
 *         TblPrintSizes, TblPrintSpecialServices
 ************************************************************/

/* Inserting [PhotographyAutomationDB].[dbo].[TblAlbums] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblAllOrderStatus] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblAtelierType] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblBooking] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblBookingStatus] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblCustomer] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblFilesError] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblOrder] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblOrderFiles] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblOrderPrint] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblOrderPrintDetails] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblOrderPrintFiles] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblOrderPrintStatus] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblOrderStatus] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblPhotographyType] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblPrintCustomerFiles] data... */


/* Inserted 0 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblPrintServicePrices] data... */

INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(1,NULL,8,2,50000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(2,NULL,9,2,50000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(3,NULL,10,2,80000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(4,NULL,11,2,100000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(5,NULL,12,2,120000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(6,NULL,13,2,150000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(7,NULL,14,2,200000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(8,NULL,15,2,350000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(10,NULL,16,2,350000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(11,NULL,10,4,220000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(12,NULL,10,5,220000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(13,NULL,11,11,400000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(15,NULL,11,4,250000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(16,NULL,12,11,450000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(17,NULL,12,4,300000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(18,NULL,12,5,300000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(19,NULL,14,10,300000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(20,NULL,14,11,600000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(21,NULL,14,4,400000);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServicePrices]([Id],[Code],[PrintSizeId],[PrintServiceId],[Price])
VALUES(22,NULL,14,5,400000);

/* Inserted 20 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblPrintServices] data... */

INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServices]([Id],[Code],[PrintServiceName],[PrintServiceDescription])
VALUES(2,N'Shasi-8mil',N'???? 8 ???',NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServices]([Id],[Code],[PrintServiceName],[PrintServiceDescription])
VALUES(3,N'Shasi-16mil',N'???? 16 ???',NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServices]([Id],[Code],[PrintServiceName],[PrintServiceDescription])
VALUES(4,N'W-GhabShi',N'??? ???? ????',NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServices]([Id],[Code],[PrintServiceName],[PrintServiceDescription])
VALUES(5,N'Br-GhabShi',N'??? ???? ???? ??',NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServices]([Id],[Code],[PrintServiceName],[PrintServiceDescription])
VALUES(6,N'BG-GhabShi',N'??? ???? ???? ?????',NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServices]([Id],[Code],[PrintServiceName],[PrintServiceDescription])
VALUES(8,N'BB-GhabShi',N'??? ???? ???? ?? ????',NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServices]([Id],[Code],[PrintServiceName],[PrintServiceDescription])
VALUES(9,N'Frame-2cm',N'???? ?? ?????',NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServices]([Id],[Code],[PrintServiceName],[PrintServiceDescription])
VALUES(10,N'Frame-4cm',N'???? ???? ?????',NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintServices]([Id],[Code],[PrintServiceName],[PrintServiceDescription])
VALUES(11,N'Ghab-Shasi',N'??? ????',NULL);

/* Inserted 9 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblPrintSizePrices] data... */

INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizePrices]([Id],[PrintSizeId],[FirstPrintPrice],[RePrintPrice],[MedicalPrice],[MedicalRePrintPrice],[LitPrintPrice],[LitPrintRePrintPrice],[ScanAndPrintPrice],[ScanAndProcessingPrice],[ItalianAlbumPagePrice],[ItalianAlbumBoundingPrice])
VALUES(1,1,180000,230000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizePrices]([Id],[PrintSizeId],[FirstPrintPrice],[RePrintPrice],[MedicalPrice],[MedicalRePrintPrice],[LitPrintPrice],[LitPrintRePrintPrice],[ScanAndPrintPrice],[ScanAndProcessingPrice],[ItalianAlbumPagePrice],[ItalianAlbumBoundingPrice])
VALUES(2,2,180000,230000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizePrices]([Id],[PrintSizeId],[FirstPrintPrice],[RePrintPrice],[MedicalPrice],[MedicalRePrintPrice],[LitPrintPrice],[LitPrintRePrintPrice],[ScanAndPrintPrice],[ScanAndProcessingPrice],[ItalianAlbumPagePrice],[ItalianAlbumBoundingPrice])
VALUES(3,3,180000,230000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizePrices]([Id],[PrintSizeId],[FirstPrintPrice],[RePrintPrice],[MedicalPrice],[MedicalRePrintPrice],[LitPrintPrice],[LitPrintRePrintPrice],[ScanAndPrintPrice],[ScanAndProcessingPrice],[ItalianAlbumPagePrice],[ItalianAlbumBoundingPrice])
VALUES(4,4,200000,250000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizePrices]([Id],[PrintSizeId],[FirstPrintPrice],[RePrintPrice],[MedicalPrice],[MedicalRePrintPrice],[LitPrintPrice],[LitPrintRePrintPrice],[ScanAndPrintPrice],[ScanAndProcessingPrice],[ItalianAlbumPagePrice],[ItalianAlbumBoundingPrice])
VALUES(5,5,200000,250000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizePrices]([Id],[PrintSizeId],[FirstPrintPrice],[RePrintPrice],[MedicalPrice],[MedicalRePrintPrice],[LitPrintPrice],[LitPrintRePrintPrice],[ScanAndPrintPrice],[ScanAndProcessingPrice],[ItalianAlbumPagePrice],[ItalianAlbumBoundingPrice])
VALUES(6,6,200000,250000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizePrices]([Id],[PrintSizeId],[FirstPrintPrice],[RePrintPrice],[MedicalPrice],[MedicalRePrintPrice],[LitPrintPrice],[LitPrintRePrintPrice],[ScanAndPrintPrice],[ScanAndProcessingPrice],[ItalianAlbumPagePrice],[ItalianAlbumBoundingPrice])
VALUES(7,7,310000,260000,NULL,NULL,100000,100000,NULL,NULL,NULL,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizePrices]([Id],[PrintSizeId],[FirstPrintPrice],[RePrintPrice],[MedicalPrice],[MedicalRePrintPrice],[LitPrintPrice],[LitPrintRePrintPrice],[ScanAndPrintPrice],[ScanAndProcessingPrice],[ItalianAlbumPagePrice],[ItalianAlbumBoundingPrice])
VALUES(8,8,150000,100000,120000,120000,0,0,0,0,NULL,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizePrices]([Id],[PrintSizeId],[FirstPrintPrice],[RePrintPrice],[MedicalPrice],[MedicalRePrintPrice],[LitPrintPrice],[LitPrintRePrintPrice],[ScanAndPrintPrice],[ScanAndProcessingPrice],[ItalianAlbumPagePrice],[ItalianAlbumBoundingPrice])
VALUES(9,9,300000,250000,150000,150000,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizePrices]([Id],[PrintSizeId],[FirstPrintPrice],[RePrintPrice],[MedicalPrice],[MedicalRePrintPrice],[LitPrintPrice],[LitPrintRePrintPrice],[ScanAndPrintPrice],[ScanAndProcessingPrice],[ItalianAlbumPagePrice],[ItalianAlbumBoundingPrice])
VALUES(15,46,230000,200000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizePrices]([Id],[PrintSizeId],[FirstPrintPrice],[RePrintPrice],[MedicalPrice],[MedicalRePrintPrice],[LitPrintPrice],[LitPrintRePrintPrice],[ScanAndPrintPrice],[ScanAndProcessingPrice],[ItalianAlbumPagePrice],[ItalianAlbumBoundingPrice])
VALUES(16,10,450000,400000,170000,170000,NULL,NULL,NULL,NULL,NULL,NULL);

/* Inserted 11 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblPrintSizes] data... */

INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(1,2,3,N'2 x 3',TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,6,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(2,3,4,N'3 x 4',TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,6,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(3,3.5,4.5,N'3.5 x 4.5',TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,6,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(4,6,4,N'6 x 4',TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,6,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(5,5,5,N'5 x 5',TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,6,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(6,5,7,N'5 x 7',TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,6,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(7,6,9,N'6 x 9',TRUE,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,6,'');
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(8,10,15,N'10 x 15',TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,1,'');
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(9,13,18,N'13 x 18',TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,1,'');
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(10,16,21,N'16 x 21',TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,1,'');
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(11,20,25,N'20 x 25',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(12,20,30,N'20 x 30',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(13,24,30,N'24 x 30',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(14,30,40,N'30 x 40',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(15,30,50,N'30 x 50',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(16,30,60,N'30 x 60',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(17,30,70,N'30 x 70',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(18,30,80,N'30 x 80',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(19,30,90,N'30 x 90',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(20,40,50,N'40 x 50',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(21,40,60,N'40 x 60',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(22,40,70,N'40 x 70',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(23,40,80,N'40 x 80',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(24,50,60,N'50 x 60',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(25,50,70,N'50 x 70',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(26,50,80,N'50 x 80',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(27,50,90,N'50 x 90',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(28,60,80,N'60 x 80',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(29,50,100,N'50 x 100',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(30,60,80,N'60 x 80',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(31,60,90,N'60 x 90',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(32,60,100,N'60 x 100',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(33,70,100,N'70 x 100',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(34,80,100,N'80 x 100',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(35,90,100,N'90 x 100',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(36,100,100,N'100 x 100',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(37,100,110,N'100 x 110',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(38,100,120,N'100 x 120',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(39,100,150,N'100 x 150',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(40,110,150,N'110 x 150',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(41,100,200,N'100 x 200',TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,1,NULL);
INSERT INTO [PhotographyAutomationDB].[dbo].[TblPrintSizes]([Id],[Width],[Height],[Name],[HasFirstPrint],[HasRePrint],[HasMedicalPhoto],[HasLitPrint],[HasScanAndProcessing],[HasAlbum],[HasItalianAlbum],[IsActive],[IsDeleted],[MinimumOrder],[Descriptions])
VALUES(46,4,4,N'4 x 4',FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,6,'');

/* Inserted 42 rows */

/* Inserting [PhotographyAutomationDB].[dbo].[TblPrintSpecialServices] data... */


/* Inserted 0 rows */

/* Successfully inserted 82 rows in 21 tables. */
