//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDescriptions
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string FileId { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime UpdatedTimestamp { get; set; }
        public string ContentType { get; set; }
    }
}
