//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAllOrderStatus
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int OrderPrintId { get; set; }
        public int StatusCode { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        public virtual TblOrderPrint TblOrderPrint { get; set; }
        public virtual TblOrder TblOrder { get; set; }
    }
}
