//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBooking
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public byte PhotographerGender { get; set; }
        public int PhotographyTypeId { get; set; }
        public int AtelierTypeId { get; set; }
        public int PersonCount { get; set; }
        public byte PrepaymentIsOk { get; set; }
        public int Submitter { get; set; }
        public int StatusId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual TblAtelierType TblAtelierType { get; set; }
        public virtual TblBookingStatus TblBookingStatus { get; set; }
        public virtual TblPhotographyType TblPhotographyType { get; set; }
        public virtual TblCustomer TblCustomer { get; set; }
    }
}
