//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDocumentPhotos
    {
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public System.Guid StreamId { get; set; }
        public int CustomerId { get; set; }
        public bool IsSelected { get; set; }
        public string path_locator { get; set; }
        public string parent_path_locator { get; set; }
    
        public virtual TblDocuments TblDocuments { get; set; }
    }
}
