//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmpRole
    {
        public int Id { get; set; }
        public Nullable<byte> EmpTypeId { get; set; }
        public Nullable<int> RoleTypeId { get; set; }
    
        public virtual TblEmployeeType TblEmployeeType { get; set; }
    }
}
