//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFilesError
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> Submitter { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> ErrorInId { get; set; }
        public string ErrorMessage { get; set; }
    
        public virtual TblBooking TblBooking { get; set; }
        public virtual TblCustomer TblCustomer { get; set; }
        public virtual TblOrder TblOrder { get; set; }
    }
}
