//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrderPrintFiles
    {
        public int Id { get; set; }
        public int OrderPrintId { get; set; }
        public string FileName { get; set; }
        public string PathLocator { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
    
        public virtual TblOrderPrint TblOrderPrint { get; set; }
    }
}
