//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrderPrintMultiPhotoOrder
    {
        public int Id { get; set; }
        public Nullable<int> OrderPrintDetailId { get; set; }
        public Nullable<System.Guid> MainPhotoStreamId { get; set; }
        public Nullable<System.Guid> StreamId { get; set; }
        public string MainPhotoFileName { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
    
        public virtual TblOrderPrintDetails TblOrderPrintDetails { get; set; }
    }
}
