//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrderFiles
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public System.Guid StreamId { get; set; }
        public string FileName { get; set; }
        public string PathLocator { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    
        public virtual TblOrder TblOrder { get; set; }
    }
}
