//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrderPrintDetails
    {
        public int Id { get; set; }
        public int OrderPrintId { get; set; }
        public System.Guid StreamId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> PrintSizeServiceId { get; set; }
        public string FileName { get; set; }
        public string RetochDescription { get; set; }
        public string CreatedDateTime { get; set; }
        public string ModifiedDateTime { get; set; }
    
        public virtual TblCustomer TblCustomer { get; set; }
        public virtual TblOrderPrint TblOrderPrint { get; set; }
        public virtual TblPrintServices_TblPrintSizePrice TblPrintServices_TblPrintSizePrice { get; set; }
    }
}
