//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrderPrint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblOrderPrint()
        {
            this.TblAllOrderStatus = new HashSet<TblAllOrderStatus>();
            this.TblOrderPrintDetails = new HashSet<TblOrderPrintDetails>();
            this.TblOrderPrintFiles = new HashSet<TblOrderPrintFiles>();
        }
    
        public int Id { get; set; }
        public int OrderId { get; set; }
        public bool OrderType { get; set; }
        public int OrderStatusId { get; set; }
        public int OrderPrintStatusId { get; set; }
        public int CustomerId { get; set; }
        public string RetochDescriptions { get; set; }
        public Nullable<int> TotalPhotos { get; set; }
        public Nullable<long> TotalPrice { get; set; }
        public Nullable<long> Payment { get; set; }
        public Nullable<long> Deposit { get; set; }
        public Nullable<long> Remaining { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAllOrderStatus> TblAllOrderStatus { get; set; }
        public virtual TblCustomer TblCustomer { get; set; }
        public virtual TblOrderPrintStatus TblOrderPrintStatus { get; set; }
        public virtual TblOrderStatus TblOrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOrderPrintDetails> TblOrderPrintDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOrderPrintFiles> TblOrderPrintFiles { get; set; }
        public virtual TblOrder TblOrder { get; set; }
    }
}
