//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPrintServices_TblPrintSizePrice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPrintServices_TblPrintSizePrice()
        {
            this.TblOrderPrintDetails = new HashSet<TblOrderPrintDetails>();
        }
    
        public int Id { get; set; }
        public int PrintServiceId { get; set; }
        public int PrintSizePriceId { get; set; }
        public string Code { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOrderPrintDetails> TblOrderPrintDetails { get; set; }
        public virtual TblPrintServices TblPrintServices { get; set; }
        public virtual TblPrintSizePrices TblPrintSizePrices { get; set; }
    }
}
