//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPrintItalianAlbums
    {
        public int Id { get; set; }
        public int PrintSizeId { get; set; }
        public int SizeName { get; set; }
        public int PagePrintPrice { get; set; }
        public int AlbumBindingPrice { get; set; }
        public string Description { get; set; }
    
        public virtual TblPrintSizes TblPrintSizes { get; set; }
    }
}
