//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPrintSizePrices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPrintSizePrices()
        {
            this.TblOrderPrintDetails = new HashSet<TblOrderPrintDetails>();
            this.TblOrderPrintDetails1 = new HashSet<TblOrderPrintDetails>();
        }
    
        public int Id { get; set; }
        public int PrintSizeId { get; set; }
        public Nullable<int> FirstPrintPrice { get; set; }
        public Nullable<int> RePrintPrice { get; set; }
        public Nullable<int> MedicalPrice { get; set; }
        public Nullable<int> MedicalRePrintPrice { get; set; }
        public Nullable<int> LitPrintPrice { get; set; }
        public Nullable<int> LitPrintRePrintPrice { get; set; }
        public Nullable<int> ScanAndPrintPrice { get; set; }
        public Nullable<int> ScanAndProcessingPrice { get; set; }
        public Nullable<int> ItalianAlbumPagePrice { get; set; }
        public Nullable<int> ItalianAlbumBoundingPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOrderPrintDetails> TblOrderPrintDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOrderPrintDetails> TblOrderPrintDetails1 { get; set; }
        public virtual TblPrintSizes TblPrintSizes { get; set; }
    }
}
