//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPrintServices_TblPrintSizePrice
    {
        public int Id { get; set; }
        public int PrintServiceId { get; set; }
        public int PrintSizePriceId { get; set; }
        public string Code { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }
    
        public virtual TblPrintServices TblPrintServices { get; set; }
        public virtual TblPrintSizePrices TblPrintSizePrices { get; set; }
    }
}
