//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<byte> Gender { get; set; }
        public string Address { get; set; }
        public string Tell { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string NationalId { get; set; }
        public Nullable<byte> CustomerType { get; set; }
        public Nullable<byte> IsMarried { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> WeddingDate { get; set; }
        public Nullable<byte> UserType { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<byte> EmployeeTypeId { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
        public Nullable<int> Submitter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual TblEmployeeType TblEmployeeType { get; set; }
    }
}
