//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte Gender { get; set; }
        public string Address { get; set; }
        public string Tell { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string NationalId { get; set; }
        public byte CustomerType { get; set; }
        public byte IsMarried { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime WeddingDate { get; set; }
        public byte UserType { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public int IsActive { get; set; }
        public int IsDeleted { get; set; }
        public int Submitter { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual TblEmployeeType TblEmployeeType { get; set; }
    }
}
