//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    
    public partial class usp_GetListOfFilesInFolder_Result1
    {
        public System.Guid StreamId { get; set; }
        public string FileName { get; set; }
        public Nullable<long> FileSize { get; set; }
    }
}
