//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    
    public partial class usp_CreateFileTableFile_Result2
    {
        public string streamId { get; set; }
        public string name { get; set; }
        public string parent_locator { get; set; }
        public string path_name { get; set; }
        public byte[] filestreamTxn { get; set; }
        public string path_locator_str { get; set; }
    }
}
