//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotographyAutomation.DateLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PrintSizesPrices
    {
        public string PrintServiceName { get; set; }
        public string SizeName { get; set; }
        public decimal SizeWidth { get; set; }
        public decimal SizeHeight { get; set; }
        public int OriginalPrintPrice { get; set; }
        public int SecondPrintPrice { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> PrintServiceId { get; set; }
        public Nullable<int> PrintSizePriceId { get; set; }
        public string Code { get; set; }
        public Nullable<int> Price { get; set; }
        public string Description { get; set; }
    }
}
